---
title: 'Practical ML: Course Project'
author: "mmcbride"
date: "21 October 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(RCurl)
library(caret)
library(tidyverse)
```

## Executive Summary


## Load and Clean Data

### Pull data into R

The training and test data are loaded from two sepeate URLs.
```{r}

trainingURL <- "https://d396qusza40orc.cloudfront.net/predmachlearn/pml-training.csv"
training <- read.csv(textConnection(getURL(trainingURL)))

testURL <- "https://d396qusza40orc.cloudfront.net/predmachlearn/pml-testing.csv"
testing <- read.csv(textConnection(getURL(testURL)))
```

The dependent variable in question is "classe". 

```{r} summary(training$classe)```





### Clean the data


## Trying Different models
```{r models, echo=FALSE}
modelLM <- lm(as.factor(classe) ~ . , data=training)



```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
